### ISSUE TITLE
Требуется добавить комментарии на страницы произведений.

### ISSUE THREAD

**Issue by semen1032** [BearPro/seterator#12]
Поступил запрос на реализацию комментариев на страницах. Пока что наиболее вероятная реализация - добавить виджет с комментариями Вконтакте (https://vk.com/dev/Comments).

**Comment by BearPro** [comment]
До сих пор не могу понять, что за булщит у нас происходит с **произведениями** и **участниками**, и как они должны быть связаны. Какую страницу ты имеешь ввиду, говоря "Страницы произведений"?

**Comment by semen1032** [comment]
Сам не понимаю, почему у пользователя не может быть отдельной вкладки со всеми его произведениями. 
Насколько я понимаю, в данный момент у нас каждое произведение должно быть закреплено за отдельным конкурсом, к которому оно писалось. Причем у одного пользователя может быть несколько участий в одном конкурсе под разными псевдонимами. 
Идея с прикреплением произведения к конкурсу кажется мне неправильной, так как уже участвовавшее произведение в одном конкурсе можно отправлять и на другой конкурс.

**Comment by semen1032** [comment]
Под страницей с произведением я подразумеваю эту страницу:
![image](https://user-images.githubusercontent.com/51064226/68542642-e858ec00-03bf-11ea-818d-2bf3ba8048f3.png)

**Comment by BearPro** [comment]
Кстати, @saner99, почему блок вконтактовских комментариев перекрашен? Это колхоз, если мы уже вытыкаем комменты из вконтакте - то втыкать надо синенькими, что бы пользователь не подумал что это такие же липовые комменты как на сайтах про таблетки для увеличения пениса.

**Comment by semen1032** [comment]
Я бы создал отдельную сущность "Произведение", для которого прописал бы поля:
- GUID автора
- Псевдоним
- Название
- Дата создания
- Конкурсы в которых участвовало (Название конкурса, Дата подачи заявки, Занятое место)

**Comment by semen1032** [comment]
> Кстати, @saner99, почему блок вконтактовских комментариев перекрашен? Это колхоз, если мы уже вытыкаем комменты из вконтакте - то втыкать надо синенькими, что бы пользователь не подумал что это такие же липовые комменты как на сайтах про таблетки для увеличения пениса.

@saner99 сильно настаивает на такой окраске, чтобы вписывалось в общую цветовую гамму.

**Comment by semen1032** [comment]
@BearPro, на странице профиля есть блок "Портфолио", в котором лежит список всех произведений автора.

**Comment by saner99** [comment]
@BearPro @semen1032 а представьте, у нас комменты, которые мы кодили сами. они оранжевые или тоже под вк будем цвет менять. Когда человек туда пишет, он уже авторизован, обычно, в браузере, так что, не должно вызывать недоверия
