### ISSUE TITLE
Страница профиля должна быть переработана.

### ISSUE THREAD

**Issue by BearPro** [BearPro/seterator#2]
От дизайнеров пришёл запрос на обновление страницы. 
Также страница содержит много placeholder'ов.

**Comment by BearPro** [comment]
@semen1032 Залей пожалуйста макет нового дизайна профиля.

**Comment by semen1032** [comment]
![image](https://user-images.githubusercontent.com/51064226/68472583-dd705100-0231-11ea-8461-f57697a27b33.png)

**Comment by semen1032** [comment]
@BearPro, начинаю верстать обновленный профиль. В скором времени понадобится контроллер к данной странице.

**Comment by semen1032** [comment]
Дизайн на странице переработан. Стоит много заглушек, жду контроллер.
