### ISSUE TITLE
Система профилей заслуживает переработки

### ISSUE THREAD

**Issue by BearPro** [BearPro/seterator#3]
Требуемые фичи:
1. Поддержка множественных профилей
2. Поддержка коротких ссылок
3. Обновление схемы БД для хранения новых данных о пользователе.

**Comment by saner99** [comment]
___информация профиля
- фото
- номер телефона, email, привязынные соцсети (+настройка видимости)
- имя пользователя (виден только юзеру)
- псевдоним (виден всем)
- страна, город, дата рождения
- о себе
- литературный статус (подтверждённое членство в союзе писателей россии, союзе российских писателей и пр.)
- рейтинг автора, организатора, жюри
- достижения (список прошедших конкурсов с возможностью скрыть/показать каждое достижение
- заявки на модерации (видно юзеру)
- портфолио (все конкурсы, в которых юзер участвовал: лого организатора, занятое место, название конкурса, название произведения, поделиться в соцсетях - видно всем)
- возможность пригласить юзера к участию в конкурсе - юзеру приходит уведомление "вас приглашают.." (для организаторов, видно только организаторам)
___на будущее: документы и соглашения, сканы паспорта и пр (pdf, jpeg, png) закрепить за юзером, чтобы он мог посмотреть их, после дополнительной авторизации (на всякий случай)

**Comment by BearPro** [comment]
@saner99 Как быть с множественными профилями?
Я сейчас вижу примерно такое устройство: у любого зарегистрированного пользователя имеется **базовый профиль**: имя, номер телефона, страна и прочее - то что связано именно с отдельным человеком, а не с его родом активности на нашем сайте. 
Далшьше, если он участвует в конкурсе - пишет стих, например - у него появляется ещё **профиль участника** - ещё одна запись в БД. Там уже специфичная информация по стихам.
И так же с другимии профилями.

Это всё проецируется на интерфейс сайта: при появлении нового профиля в БД на веб-странице профиля пользователя появляется новый блок, а может быть вообще отдельная веб-страница представляющая каждый профиль и одна какая-нибудь сводная.

**Comment by saner99** [comment]
@BearPro  да всё так. для модераторов жюри, авторов одна страница, которая меняется, для организаторов (физ или юр не важно) отдельная страница организатора

**Comment by BearPro** [comment]
В #26 добавлен api-контроллер для профилей. Все темы с отдельными страницами или изменением страниц можно выполнить на стороне клиента. 
Данные хранимые в профиле ничем не ограничены.
