### ISSUE TITLE
Необходимо создать счетчик времени до окончания приема заявок на конкурс.

### ISSUE THREAD

**Issue by semen1032** [BearPro/seterator#9]
Счетчик должен отображать часы и минуты до окончания приема заявок. Счетчик динамический и обновляет значение каждую минуту. Один из дизайнов счетчика:
![image](https://user-images.githubusercontent.com/51064226/68490242-b463b680-0259-11ea-8adc-921b74e875b0.png)

**Comment by BearPro** [comment]
Семён, вместо того чтобы напрямую коммитить в мастер (или мерджить свою ветку с ним), можно делать pull request для ветки. Это прикольнее, тогда у нас будет движ ещё и на одной вкладке, а ещё будет видно чем закончилась задача: что она не просто закрыта, а что этот ишью упомянут в пулл-реквесте, пулл-реквест одобрен, и после этого ишью закрыт.
